import { MultiRankTalent, SingleRankTalent } from "@/lib/classes";
import { talentNames } from "@/lib/constants";
import { TalentTier, TalentTree } from "@/lib/types";

const tier1: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.warrior.improvedHeroicStrike,
    "ability_rogue_ambush",
    ["Reduces the cost of your Heroic Strike ability by ", " Rage."],
    [[1, 2, 3]],
  ),
  new MultiRankTalent(
    talentNames.warrior.deflection,
    "ability_parry",
    ["Increases your Parry chance by ", "%."],
    [[1, 2, 3, 4, 5]],
  ),
  new MultiRankTalent(
    talentNames.warrior.improvedRend,
    "ability_gouge",
    ["Increases the Bleed damage done by your Rend ability by ", "%."],
    [[12, 23, 35]],
  ),
  null,
];

const tier2: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.warrior.improvedCharge,
    "ability_warrior_charge",
    ["Increases the Rage generated by your Charge ability by ", "."],
    [[3, 6]],
  ),
  new MultiRankTalent(
    talentNames.warrior.improvedTacticalMastery,
    "spell_nature_enchantarmor",
    [
      "Tactical Mastery lets you retain up to an additional ",
      " Rage when you change stances.",
    ],
    [[3, 6, 9, 12, 15]],
  ),
  null,
  new MultiRankTalent(
    talentNames.warrior.improvedOverpower,
    "inv_sword_05",
    [
      "Increases the critical strike chance of your Overpower ability by ",
      "%.",
    ],
    [[25, 50]],
  ),
];

const tier3: TalentTier = [
  null,
  null,
  new SingleRankTalent(
    talentNames.warrior.angerManagement,
    "spell_holy_blessingofstamina",
    "Generates 1 Rage every 3 sec while in combat, and reduces Rage loss while out of combat by 30%.",
    talentNames.warrior.improvedTacticalMastery,
  ),
  new MultiRankTalent(
    talentNames.warrior.deepWounds,
    "ability_backstab",
    [
      "Your critical strikes cause your opponent to Bleed, dealing ",
      "% of your melee weapon's average damage over 12 sec.",
    ],
    [[20, 40, 60]],
    talentNames.warrior.improvedRend,
  ),
  null,
];

const tier4: TalentTier = [
  null,
  new SingleRankTalent(
    talentNames.warrior.spearingStrike,
    "inv_spear_01",
    "A brutal attack that deals 40% weapon damage, plus an additional 80% weapon damage against Giants, Dragonkin, and mounted targets.",
  ),
  new MultiRankTalent(
    talentNames.warrior.twoHandedWeaponSpecialization,
    "inv_axe_09",
    ["Increases the damage you deal with two-handed melee weapons by ", "%."],
    [[1, 2, 3]],
  ),
  new MultiRankTalent(
    talentNames.warrior.impale,
    "ability_searingarrow",
    ["Increases the critical strike damage bonus of your abilities by ", "%."],
    [[10, 20]],
  ),
  null,
];

const tier5: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.warrior.bloodthrill,
    "inv_sword_01",
    [
      "Your Main Hand melee attacks against enemies afflicted by your Rend have a ",
      "% chance to allow the use of your Overpower ability on the target. Lasts 6 sec.",
    ],
    [[4, 8, 12, 16, 20]],
  ),
  new SingleRankTalent(
    talentNames.warrior.sweepingStrikes,
    "ability_rogue_slicedice",
    "Your next 5 melee attacks strike an additional nearby opponent.",
  ),
  // TODO: check manually: description contains markup
  new MultiRankTalent(
    talentNames.warrior.weaponmaster,
    "garrison_weaponupgrade",
    [
      'Gives your melee weapon attacks a benefit depending on the weapon.<br /><br />    <span style="color: #FFFFFF">Axe/Polearm:</span> Increases your<br />    critical strike chance by ',
      '%.<br /><br />    <span style="color: #FFFFFF">Mace/Staff:</span> Your attacks ignore<br />    ',
      '% of your target\'s armor.<br /><br />    <span style="color: #FFFFFF">Sword:</span> Your successful melee <br />    attacks have a ',
      "% chance to <br />    trigger an extra attack on the <br />    target.",
    ],
    [
      [1, 2, 3, 4, 5],
      [3, 6, 9, 12, 15],
      [1, 2, 3, 4, 5],
    ],
  ),
  null,
];

const tier6: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.warrior.improvedSlam,
    "ability_warrior_decisivestrike",
    [
      "Reduces the global cooldown and cast time of your Slam ability by ",
      " sec. In addition, Slam no longer interrupts or delays your melee swing and Slam's cooldown is reduced by 3.0 sec.",
    ],
    [[0.25, "0.50"]],
  ),
  null,
  new MultiRankTalent(
    talentNames.warrior.improvedHamstring,
    "ability_shockwave",
    [
      "Gives your Hamstring ability a ",
      "% chance to immobilize the target for 5 sec.",
    ],
    [[5, 10, 15]],
  ),
  null,
];

const tier7: TalentTier = [
  null,
  null,
  new SingleRankTalent(
    talentNames.warrior.mortalStrike,
    "ability_warrior_savageblow",
    "A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.",
    talentNames.warrior.sweepingStrikes,
  ),
  null,
  null,
];

export const arms: TalentTree = {
  name: "Arms",
  icon: "ability_warrior_savageblow",
  tiers: {
    tier1,
    tier2,
    tier3,
    tier4,
    tier5,
    tier6,
    tier7,
  },
};
