import { MultiRankTalent, SingleRankTalent } from "../../classes";
import { talentNames } from "../../constants";
import { TalentTier } from "../../types";

const tier1: TalentTier = [
  null,
  null,
  new MultiRankTalent(
    talentNames.boomingVoice,
    "spell_nature_purge",
    [
      "Increases the area of effect of your Shouts by ",
      "% and reduces their Rage cost by ",
      "%.",
    ],
    [
      ["10", "20", "30", "40", "50"],
      ["5", "10", "15", "20", "25"],
    ],
  ),
  new MultiRankTalent(
    talentNames.cruelty,
    "ability_rogue_eviscerate",
    [
      "Improves your chance to get a critical strike with melee attacks by ",
      "%.",
    ],
    [["1", "2", "3", "4", "5"]],
  ),
  null,
];

const tier2: TalentTier = [
  null,
  null,
  new MultiRankTalent(
    talentNames.lingeringRage,
    "ability_warrior_secondwind",
    [
      "Increases the time before your Rage begins to decay after leaving combat by ",
      " sec.",
    ],
    [["2", "4", "6", "8", "10"]],
  ),
  new MultiRankTalent(
    talentNames.unbridledWrath,
    "spell_nature_stoneclawtotem",
    [
      "Gives you a ",
      "% chance to generate 1 additional Rage when you deal melee damage with a weapon.",
    ],
    [["12", "24", "36", "48", "60"]],
  ),
  null,
];

const tier3: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.furiousPrecision,
    "ability_warrior_incite",
    ["Increases your chance to hit with off-hand attacks by ", "%."],
    [["4", "7", "10"]],
  ),
  new SingleRankTalent(
    talentNames.piercingHowl,
    "spell_shadow_deathscream",
    "Causes all nearby enemies to be Dazed, reducing movement speed by 50% for 6 sec.",
  ),
  new MultiRankTalent(
    talentNames.bloodCraze,
    "spell_shadow_summonimp",
    [
      "Regenerates ",
      "% of your total Health over 6 sec after being the victim of a critical strike or suffering more than 20% of your maximum Health from a single attack.",
    ],
    [["1", "2", "3"]],
  ),
  null,
];

const tier4: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.dualWieldSpecialization,
    "ability_dualwield",
    [
      "Increases the damage done by your off-hand weapon by ",
      "% and the Rage generated by your off-hand attacks by ",
      "%.",
    ],
    [
      ["5", "10", "15", "20", "25"],
      ["10", "20", "30", "40", "50"],
    ],
  ),
  new SingleRankTalent(
    talentNames.ragingBlows,
    "ability_whirlwind",
    "Causes your Whirlwind to also strike with your Off Hand weapon, and reduces the Rage cost of your Cleave ability by 2.",
  ),
  new MultiRankTalent(
    talentNames.enrage,
    "spell_shadow_unholyfrenzy",
    [
      "Gives you a 30% chance to deal ",
      "% increased Physical damage for 12 sec after being the victim of any damaging attack.",
    ],
    [["2", "4", "6", "8", "10"]],
  ),
  new MultiRankTalent(
    talentNames.improvedExecute,
    "inv_sword_48",
    ["Reduces the Rage cost of your Execute ability by ", "."],
    [["3", "5"]],
  ),
];

const tier5: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.improvedBerserkerRage,
    "spell_nature_ancestralguardian",
    [
      "Your Berserker Rage ability will instantly generate ",
      " Rage and has a ",
      "% chance to remove all movement impairing effects when activated.",
    ],
    [
      ["5", "10"],
      ["50", "100"],
    ],
  ),
  new SingleRankTalent(
    talentNames.deathWish,
    "spell_shadow_deathpact",
    "When activated, increases your Physical damage done by 20% and makes you immune to Fear effects, but increases all damage you take by 5%. Lasts 30 sec.",
  ),
  null,
  new MultiRankTalent(
    talentNames.improvedIntercept,
    "ability_rogue_sprint",
    ["Reduces the cooldown of your Intercept ability by ", " sec."],
    [["5", "10"]],
  ),
];

const tier6: TalentTier = [
  null,
  null,
  new MultiRankTalent(
    talentNames.flurry,
    "ability_ghoulfrenzy",
    [
      "Increases your melee attack speed by ",
      "% for your next 3 swings after dealing a melee critical strike.",
    ],
    [["5", "10", "15", "20", "25"]],
    talentNames.deathWish,
  ),
  new MultiRankTalent(
    talentNames.goreDrinker,
    "racial_troll_berserk",
    [
      "Your Enrage, Berserker Rage, Bloodrage, Death Wish, and Bloodthirst abilities cause your next 3 melee attacks to restore ",
      "% of your maximum Health.",
    ],
    [["0.5", "1.0"]],
    talentNames.enrage,
  ),
  null,
];

const tier7: TalentTier = [
  null,
  null,
  new SingleRankTalent(
    talentNames.bloodthirst,
    "spell_nature_bloodlust",
    "Instantly attack the target causing damage equal to 35% of your Attack Power plus 30 and increasing your movement speed by 10% for 10 sec.",
  ),
  null,
  null,
];

export const fury = {
  tier1,
  tier2,
  tier3,
  tier4,
  tier5,
  tier6,
  tier7,
};
