import { MultiRankTalent, SingleRankTalent } from "../../classes";
import { talentNames } from "../../constants";
import { TalentTier } from "../../types";

const tier1: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.warrior.improvedBloodrage,
    "ability_racial_bloodrage",
    ["Increases all the Rage generated by your Bloodrage ability by ", "%."],
    [["25", "50"]],
  ),
  new MultiRankTalent(
    talentNames.warrior.shieldSpecialization,
    "inv_shield_06",
    [
      "Increases your chance to Block attacks with your shield by ",
      "% and grants you a ",
      "% chance to generate 5 Rage when you Block.",
    ],
    [
      ["1", "2", "3", "4", "5"],
      ["20", "40", "60", "80", "100"],
    ],
  ),
  new MultiRankTalent(
    talentNames.warrior.ironWill,
    "spell_magic_magearmor",
    [
      "Reduces the duration of Stun and Fear effects inflicted on you by ",
      "%.",
    ],
    [["3", "6", "9", "12", "15"]],
  ),
  null,
];

const tier2: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.warrior.anticipation,
    "spell_nature_mirrorimage",
    ["Increases your Defense Skill by ", "."],
    [["4", "8", "12", "16", "20"]],
  ),
  null,
  new MultiRankTalent(
    talentNames.warrior.improvedRevenge,
    "ability_warrior_revenge",
    ["Increases damage dealt by your Revenge ability by ", "%."],
    [["20", "40", "60"]],
  ),
  new MultiRankTalent(
    talentNames.warrior.improvedThunderClap,
    "ability_thunderclap",
    ["Reduces the Rage cost of your Thunder Clap ability by ", "."],
    [["2", "4", "6"]],
  ),
];

const tier3: TalentTier = [
  null,
  new SingleRankTalent(
    talentNames.warrior.lastStand,
    "spell_holy_ashestoashes",
    "When activated, this ability temporarily grants you 30% of your maximum health for 20 sec. After the effect expires, the health is lost.",
  ),
  new MultiRankTalent(
    talentNames.warrior.masterOfDefense,
    "ability_warrior_shieldguard",
    [
      "Grants you a ",
      "% chance to generate 5 Rage when you Dodge or Parry while a shield is equipped.",
    ],
    [["50", "100"]],
    talentNames.warrior.shieldSpecialization,
  ),
  new MultiRankTalent(
    talentNames.warrior.improvedDisarm,
    "ability_warrior_disarm",
    ["Reduces the cooldown of your Disarm ability by ", " secs."],
    [["7", "13", "20"]],
  ),
  new MultiRankTalent(
    talentNames.warrior.defiance,
    "ability_warrior_innerrage",
    [
      "Increases all threat generated in Defensive stance by an additional ",
      "% while a shield is equipped.",
    ],
    [["5", "10", "15"]],
  ),
];

const tier4: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.warrior.improvedSunderArmor,
    "ability_warrior_sunder",
    ["Reduces the Rage cost of your Sunder Armor ability by ", "."],
    [["1", "2", "3"]],
  ),
  new SingleRankTalent(
    talentNames.warrior.vanguard,
    "ability_warrior_shieldcharge",
    "Your Charge ability is now usable while in Defensive Stance.",
  ),
  new MultiRankTalent(
    talentNames.warrior.improvedShieldBash,
    "ability_warrior_shieldbash",
    [
      "Gives your Shield Bash ability a ",
      "% chance to Silence the target for 3 sec.",
    ],
    [["50", "100"]],
  ),
  null,
];

const tier5: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.warrior.improvedShieldWall,
    "ability_warrior_shieldwall",
    ["Reduces the cooldown of your Shield Wall ability by ", " min."],
    [["5.5", "11.0"]],
  ),
  new SingleRankTalent(
    talentNames.warrior.concussionBlow,
    "ability_thunderbolt",
    "Stuns the target for 5 sec.",
  ),
  new MultiRankTalent(
    talentNames.warrior.focusedRage,
    "ability_warrior_focusedrage",
    ["Reduces the Rage cost of your offensive abilities by ", "."],
    [["1", "2", "3"]],
  ),
  null,
];

const tier6: TalentTier = [
  null,
  null,
  null,
  new MultiRankTalent(
    talentNames.warrior.bastion,
    "inv_shield_04",
    ["Increases all damage you deal by ", "% while a shield is equipped."],
    [["2", "4", "6", "8", "10"]],
  ),
  null,
];

const tier7: TalentTier = [
  null,
  null,
  new SingleRankTalent(
    talentNames.warrior.shieldSlam,
    "inv_shield_05",
    "Slam the target with your shield, causing 421 to 439 damage, increased by your Block Value, and has a 50% chance of dispelling 1 magic effect on the target. Causes a very high amount of threat.",
    talentNames.warrior.concussionBlow,
  ),
  null,
  null,
];

export const protection = {
  tier1,
  tier2,
  tier3,
  tier4,
  tier5,
  tier6,
  tier7,
};
