import { MultiRankTalent, SingleRankTalent } from "../../classes";
import { talentNames } from "../../constants";
import { TalentTier } from "../../types";

const tier1: TalentTier = [
  null,
  null,
  new MultiRankTalent(
    talentNames.toughness,
    "spell_holy_devotion",
    ["Increases your armor value from items by ", "%."],
    [["2", "4", "6", "8", "10"]],
  ),
  new MultiRankTalent(
    talentNames.redoubt,
    "ability_defend",
    [
      "Damaging melee attacks against you have a 10% chance to increase your chance to block by ",
      "%.  Lasts 10 sec or 5 blocks.",
    ],
    [["4", "8", "12", "16", "20"]],
  ),
  null,
];

const tier2: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.precision,
    "ability_rogue_ambush",
    ["Improves your chance to hit by ", "%."],
    [["1", "2", "3"]],
  ),
  new MultiRankTalent(
    talentNames.guardiansFavor,
    "spell_holy_sealofprotection",
    [
      "Reduces the cooldown of your Blessing of Protection by ",
      " min and increases the duration of your Blessing of Freedom by ",
      " sec.",
    ],
    [
      ["1", "2"],
      ["3", "6"],
    ],
  ),
  null,
  new MultiRankTalent(
    talentNames.anticipation,
    "spell_magic_lesserinvisibilty",
    ["Increases your Defense Skill by ", "."],
    [["4", "8", "12", "16", "20"]],
  ),
];

const tier3: TalentTier = [
  null,
  new SingleRankTalent(
    talentNames.improvedSealOfFury,
    "spell_holy_righteousnessaura",
    "When Seal of Fury's shield is fully absorbed, restore 0 Mana, increased by 15% per level the attacker is above you, up to 45%.",
  ),
  new MultiRankTalent(
    talentNames.improvedRighteousFury,
    "spell_holy_sealoffury",
    ["While Righteous Fury is active, all damage taken is reduced by ", "%."],
    [["2", "4", "6"]],
  ),
  new MultiRankTalent(
    talentNames.shieldSpecialization,
    "inv_shield_06",
    [
      "Increases the amount of damage absorbed by your shield by ",
      "%, and gives your blocks a ",
      "% chance to restore 6% of your maximum Mana.  May only occur once every 3 sec.",
    ],
    [
      ["10", "20", "30"],
      ["33", "66", "100"],
    ],
    talentNames.redoubt,
  ),
  new MultiRankTalent(
    talentNames.sacredDuty,
    "spell_holy_divineintervention",
    [
      "Increases your total Stamina by ",
      "% and reduces the cooldown of your Divine Shield, Divine Protection, and Templar's Bulwark spells by ",
      " sec.",
    ],
    [
      ["2", "4"],
      ["30", "60"],
    ],
  ),
];

const tier4: TalentTier = [
  null,
  new SingleRankTalent(
    talentNames.swiftJudgement,
    "ability_paladin_judgementred",
    "Finishes the remaining cooldown on your Judgement ability and reduces the Mana cost of your next Judgement by 100%.",
    talentNames.improvedSealOfFury,
  ),
  new MultiRankTalent(
    talentNames.oneHandedWeaponSpecialization,
    "inv_sword_20",
    ["Increases the damage you deal with one-handed melee weapons by ", "%."],
    [["3", "7", "10"]],
  ),
  new MultiRankTalent(
    talentNames.improvedHammerOfJustice,
    "spell_holy_sealofmight",
    ["Decreases the cooldown of your Hammer of Justice spell by ", " sec."],
    [["5", "10", "15"]],
  ),
  null,
];

const tier5: TalentTier = [
  null,
  null,
  // TODO: check manually: description contains markup
  new SingleRankTalent(
    talentNames.templarsBulwark,
    "ability_paladin_shieldofthetemplar",
    "When activated, this ability grants you an absorb shield equal to 100% of your maximum health for 8 sec. Applies Forbearance for 1 min. Cannot be cast while Forbearance is active.<!--cooldown:1224697:4 min cooldown-->",
  ),
  new MultiRankTalent(
    talentNames.reckoning,
    "spell_holy_blessingofstrength",
    [
      "Gives you a ",
      "% chance to gain an extra attack after Blocking a melee attack and a ",
      "% chance to gain an extra attack after being the victim of a non-periodic critical strike.",
    ],
    [
      ["8", "16", "24", "32", "40"],
      ["20", "40", "60", "80", "100"],
    ],
  ),
  null,
];

const tier6: TalentTier = [
  null,
  null,
  null,
  new MultiRankTalent(
    talentNames.ironCreed,
    "spell_holy_improvedresistanceauras",
    [
      "Increases the threat generated by your Holy Strike ability by ",
      "%. While Righteous Fury is active, Holy Strike also reduces your damage taken by ",
      "% for 6 sec.",
    ],
    [
      ["5", "10", "15", "20", "25"],
      ["2", "4", "6", "8", "10"],
    ],
  ),
  null,
];

const tier7: TalentTier = [
  null,
  null,
  new SingleRankTalent(
    talentNames.holyShield,
    "spell_holy_blessingofprotection",
    "Increases chance to block by 30% for 10 sec, and deals 110 Holy damage for each attack blocked while active.  Damage caused by Holy Shield causes 20% additional threat. Each block expends a charge. 4 charges.",
    talentNames.templarsBulwark,
  ),
  null,
  null,
];

export const protection = {
  tier1,
  tier2,
  tier3,
  tier4,
  tier5,
  tier6,
  tier7,
};
