import { MultiRankTalent, SingleRankTalent } from "@/lib/classes";
import { talentNames } from "@/lib/constants";
import { TalentTier, TalentTree } from "@/lib/types";

const tier1: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.shaman.earthsGrasp,
    "spell_nature_stoneclawtotem",
    [
      "Increases the health of your Stoneclaw Totem by ",
      "% and the radius of your Earthbind Totem by ",
      "%.",
    ],
    [
      [25, 50],
      [10, 20],
    ],
  ),
  new MultiRankTalent(
    talentNames.shaman.thunderingStrikes,
    "ability_thunderbolt",
    [
      "Improves your chance to get a critical strike with all spells and attacks by ",
      "%.",
    ],
    [[1, 2, 3, 4, 5]],
  ),
  new MultiRankTalent(
    talentNames.shaman.ancestralKnowledge,
    "spell_shadow_grimward",
    ["Increases your Intellect by ", "%."],
    [[2, 4, 6, 8, 10]],
  ),
  null,
];

const tier2: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.shaman.guardianTotems,
    "spell_nature_stoneskintotem",
    [
      "Increases the amount of damage reduced by your Stoneskin Totem and Windwall Totem by ",
      "% and reduces the cooldown of your Grounding Totem by ",
      " sec.",
    ],
    [
      [10, 20],
      [1, 2],
    ],
  ),
  new MultiRankTalent(
    talentNames.shaman.mentalDexterity,
    "spell_nature_mentalquickness",
    [
      "Increases your Attack Power by an amount equal to ",
      "% of your Intellect.",
    ],
    [[33, 67, 100]],
  ),
  new MultiRankTalent(
    talentNames.shaman.improvedGhostWolf,
    "spell_nature_spiritwolf",
    [
      "Reduces the cast time of your Ghost Wolf spell by ",
      " sec, and Ghost Wolf may be used indoors.",
    ],
    [["1.0", "3.0"]],
  ),
  new MultiRankTalent(
    talentNames.shaman.improvedLightningShield,
    "spell_nature_lightningshield",
    ["Increases the damage done by your Lightning Shield orbs by ", "%."],
    [[5, 10, 15]],
  ),
];

const tier3: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.shaman.elementalWeapons,
    "spell_fire_flametounge",
    [
      "Increases the melee attack power bonus of your Rockbiter Weapon by ",
      "%, your Windfury Weapon effect by ",
      "% and increases the damage caused by your Flametongue Weapon and Frostbrand Weapon by ",
      "%.",
    ],
    [
      [7, 13, 20],
      [13, 27, 40],
      [5, 10, 15],
    ],
  ),
  null,
  new SingleRankTalent(
    talentNames.shaman.shamanisticFocus,
    "spell_nature_elementalabsorption",
    "Reduces the mana cost of your Shock and Lightning Shield spells by 45%.",
  ),
  new MultiRankTalent(
    talentNames.shaman.anticipation,
    "spell_nature_mirrorimage",
    ["Increases your chance to dodge by an additional ", "%."],
    [[2, 4, 6]],
  ),
];

const tier4: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.shaman.toughness,
    "spell_holy_devotion",
    ["Increases your Stamina by ", "%."],
    [[2, 4, 6, 8, 10]],
  ),
  new MultiRankTalent(
    talentNames.shaman.flurry,
    "ability_ghoulfrenzy",
    [
      "Increases your attack speed by ",
      "% for your next 3 swings after dealing a melee critical strike.",
    ],
    [[5, 10, 15, 20, 25]],
    talentNames.shaman.mentalDexterity,
  ),
  new SingleRankTalent(
    talentNames.shaman.stormstrike,
    "ability_shaman_stormstrike",
    "Instantly strike for normal weapon damage and increase the damage you deal to the target with your next Lightning Bolt, Chain Lightning, or Earth Shock spell by 20% for 12 sec.",
  ),
  null,
];

const tier5: TalentTier = [
  null,
  new SingleRankTalent(
    talentNames.shaman.spiritWeapons,
    "ability_parry",
    "Gives a chance to parry enemy melee attacks, reduces all threat generated by your attacks by 30% while Rockbiter Weapon is not active, and increases all threat generated by 30% while Rockbiter Weapon is active.",
  ),
  new MultiRankTalent(
    talentNames.shaman.mentalQuickness,
    "spell_nature_sleep",
    [
      "Increases your spell damage and healing by up to ",
      "% of your Intellect.",
    ],
    [[15, 30]],
  ),
  new MultiRankTalent(
    talentNames.shaman.improvedStormstrike,
    "spell_shaman_improvedstormstrike",
    [
      "When you Stormstrike, you have a ",
      "% chance to gain 50% mana regeneration while casting spells for 15 sec, and Stormstrike's cooldown has a ",
      "% chance to reset each time you Dodge or Parry.",
    ],
    [
      [50, 100],
      [50, 100],
    ],
    talentNames.shaman.stormstrike,
  ),
  null,
];

const tier6: TalentTier = [
  null,
  null,
  null,
  new MultiRankTalent(
    talentNames.shaman.maelstromWeapon,
    "spell_shaman_maelstromweapon",
    [
      "When you deal damage with a melee attack, you have a chance to reduce the cast time and Mana cost of your next Lightning Bolt spell by ",
      "%. Stacks up to 5 times. Lasts 30 sec.",
    ],
    [[4, 8, 12, 16, 20]],
  ),
  null,
];

const tier7: TalentTier = [
  null,
  null,
  new SingleRankTalent(
    talentNames.shaman.rageOfTheFarseer,
    "spell_nature_bloodlust",
    "Increases your attack speed by 30% for 25 sec.",
    talentNames.shaman.mentalQuickness,
  ),
  null,
  null,
];

export const enhancement: TalentTree = {
  name: "Enhancement",
  icon: "spell_nature_lightningshield",
  tiers: {
    tier1,
    tier2,
    tier3,
    tier4,
    tier5,
    tier6,
    tier7,
  },
};
