import { MultiRankTalent, SingleRankTalent } from "../../classes";
import { talentNames } from "../../constants";
import { TalentTier } from "../../types";

const tier1: TalentTier = [
  null,
  null,
  new MultiRankTalent(
    talentNames.shaman.improvedHealingWave,
    "spell_nature_magicimmunity",
    ["Reduces the casting time of your Healing Wave spell by ", " sec."],
    [[0.1, 0.2, 0.3, 0.4, 0.5]],
  ),
  new MultiRankTalent(
    talentNames.shaman.totemicFocus,
    "spell_nature_moonglow",
    [
      "Reduces the Mana cost of your totems and any spells that summon or move them by ",
      "%.",
    ],
    [[5, 10, 15, 20, 25]],
  ),
  null,
];

const tier2: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.shaman.mindfulness,
    "spell_nature_sleep",
    ["Allows ", "% of your Mana regeneration to continue while casting."],
    [[17, 33, 50]],
  ),
  new MultiRankTalent(
    talentNames.shaman.naturalGrace,
    "spell_nature_healingtouch",
    ["Reduces the threat generated by your spells by ", "%."],
    [[5, 10, 15]],
  ),
  new MultiRankTalent(
    talentNames.shaman.tidalFocus,
    "spell_frost_manarecharge",
    [
      "Reduces the Mana cost of your healing spells by ",
      "% and improves your chance to hit by ",
      "%.",
    ],
    [
      [1, 2, 3, 4, 5],
      [1, 2, 3, 4, 5],
    ],
  ),
  new MultiRankTalent(
    talentNames.shaman.improvedReincarnation,
    "spell_nature_reincarnation",
    [
      "Reduces the cooldown of your Reincarnation spell by ",
      " min, increases your maximum health by ",
      "%, and increases the amount of health and Mana you reincarnate with by an additional ",
      "%.",
    ],
    [
      [10, 20],
      [2, 4],
      [10, 20],
    ],
  ),
];

const tier3: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.shaman.ancestralHealing,
    "spell_nature_undyingstrength",
    [
      "Increases your target's armor value by ",
      "% for 15 sec after getting a critical effect from one of your healing spells.",
    ],
    [[8, 17, 25]],
  ),
  new MultiRankTalent(
    talentNames.shaman.healingFocus,
    "spell_nature_healingwavelesser",
    [
      "Gives you a ",
      "% chance to avoid interruption caused by damage while casting any healing spell.",
    ],
    [[23, 47, 70]],
  ),
  // TODO: check manually: description contains markup
  new SingleRankTalent(
    talentNames.shaman.waterShield,
    "ability_shaman_watershield",
    "The caster is surrounded by 3 globes of water. When a spell, melee, or ranged attack hits the caster or when one of the caster's healing spells gets a critical result, 2% of maximum mana is restored to the caster, expending one water globe. Only one globe will activate every few seconds.  Lasts 10 min.<br /><br />Only one Elemental Shield can be active on the Shaman at any one time.",
  ),
  null,
];

const tier4: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.shaman.tidalMastery,
    "spell_nature_tranquility",
    ["Increases the critical effect chance of your healing spells by ", "%."],
    [[1, 2, 3, 4, 5]],
  ),
  new MultiRankTalent(
    talentNames.shaman.restorativeTotems,
    "spell_nature_manaregentotem",
    [
      "Increases the effect of your Mana Spring Totem by ",
      "% and increases the effect of your Healing Stream Totem by ",
      "%.",
    ],
    [
      [5, 10, 15, 20, 25],
      [10, 20, 30, 40, 50],
    ],
  ),
  new SingleRankTalent(
    talentNames.shaman.manaTideTotem,
    "spell_frost_summonwaterelemental",
    "Summons a Mana Tide Totem with 5 health at the feet of the caster for 12 sec that restores 88 mana every 3 seconds to group members within 30 yards.",
  ),
  null,
];

const tier5: TalentTier = [
  null,
  null,
  new MultiRankTalent(
    talentNames.shaman.healingWay,
    "spell_nature_healingway",
    ["Increases the amount healed by your Healing Wave spell by ", "%."],
    [[8, 17, 25]],
  ),
  new SingleRankTalent(
    talentNames.shaman.naturesSwiftness,
    "spell_nature_ravenform",
    "When activated, your next Nature spell with a casting time less than 10 sec. becomes an instant cast spell.",
  ),
  null,
];

const tier6: TalentTier = [
  null,
  null,
  null,
  new MultiRankTalent(
    talentNames.shaman.purification,
    "spell_frost_wizardmark",
    ["Increases the effectiveness of your healing spells by ", "%."],
    [[2, 4, 6, 8, 10]],
  ),
  null,
];

const tier7: TalentTier = [
  null,
  null,
  // TODO: check manually: description contains markup
  new SingleRankTalent(
    talentNames.shaman.riptide,
    "spell_nature_riptide",
    "Heals a friendly target for <!--ppl40:48:480:370-->486 to 534, an additional 445 over 15 sec, and increases the effectiveness of your Chain Heal casts directly on that target by 25%.",
    talentNames.shaman.healingWay,
  ),
  null,
  null,
];

export const restoration = {
  tier1,
  tier2,
  tier3,
  tier4,
  tier5,
  tier6,
  tier7,
};
