import { MultiRankTalent, SingleRankTalent } from "../../classes";
import { talentNames } from "../../constants";
import { TalentTier } from "../../types";

const tier1: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.priest.powerInLight,
    "spell_holy_searinglight",
    [
      "Your Smite and Penance spells deal ",
      "% increased damage to targets afflicted with your Holy Fire.",
    ],
    [["2", "4", "6", "8", "10"]],
  ),
  new MultiRankTalent(
    talentNames.priest.wandSpecialization,
    "inv_wand_01",
    ["Increases your damage with Wands by ", "%."],
    [["13", "25"]],
  ),
  new MultiRankTalent(
    talentNames.priest.twinDisciplines,
    "spell_holy_sealofvengeance",
    ["Increases the damage and healing of your instant cast spells by ", "%."],
    [["1", "2", "3", "4", "5"]],
  ),
  null,
];

const tier2: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.priest.silentResolve,
    "spell_nature_manaregentotem",
    [
      "Reduces the threat generated by your Holy spells by ",
      "% and reduces the duration of Stun, Fear, and Silence effects inflicted on you by ",
      "%.",
    ],
    [
      ["10", "20", "30"],
      ["5", "10", "15"],
    ],
  ),
  new MultiRankTalent(
    talentNames.priest.holyPrecision,
    "spell_holy_divineillumination",
    ["Improves your chance to hit with Holy spells by ", "%."],
    [["6", "12", "18"]],
  ),
  new MultiRankTalent(
    talentNames.priest.improvedPowerWordShield,
    "spell_holy_powerwordshield",
    ["Increases the damage absorbed by your Power Word: Shield by ", "%."],
    [["7", "14", "20"]],
  ),
  new MultiRankTalent(
    talentNames.priest.martyrdom,
    "spell_nature_tranquility",
    [
      "Gives you a ",
      "% chance to gain Focused Casting for 6 sec after being the victim of a melee or ranged critical strike. The Focused Casting effect prevents you from losing casting time when taking damage and increases your resistance to Interrupt effects by 20%.",
    ],
    [["50", "100"]],
  ),
];

const tier3: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.priest.mentalAgility,
    "ability_hibernation",
    [
      "Reduces the mana cost of your Smite, Holy Fire, and instant cast spells by ",
      "%.",
    ],
    [["3", "7", "10"]],
  ),
  new SingleRankTalent(
    talentNames.priest.innerFocus,
    "spell_frost_windwalkon",
    "When activated, reduces the Mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is a non-periodic spell and capable of a critical effect.",
  ),
  null,
  new MultiRankTalent(
    talentNames.priest.meditation,
    "spell_nature_sleep",
    ["Allows ", "% of your Mana regeneration to continue while casting."],
    [["17", "33", "50"]],
  ),
];

const tier4: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.priest.improvedInnerFire,
    "spell_holy_innerfire",
    [
      "Increases the Armor bonus of your Inner Fire spell by ",
      "% and increases its total charges by ",
      ".",
    ],
    [
      ["15", "30", "45"],
      ["4", "8", "12"],
    ],
  ),
  new MultiRankTalent(
    talentNames.priest.mentalStrength,
    "spell_nature_enchantarmor",
    ["Increases your total Intellect by ", "%."],
    [["3", "6", "9", "12", "15"]],
  ),
  new SingleRankTalent(
    talentNames.priest.soulWarding,
    "spell_holy_pureofheart",
    "Reduces the cooldown on your Power Word: Shield spell by 4 sec and reduces its mana cost by 15%.",
    talentNames.priest.improvedPowerWordShield,
  ),
  new MultiRankTalent(
    talentNames.priest.improvedManaBurn,
    "spell_shadow_manaburn",
    ["Reduces the casting time of your Mana Burn spell by ", " sec."],
    [["0.5", "1.0"]],
  ),
];

const tier5: TalentTier = [
  null,
  null,
  new SingleRankTalent(
    talentNames.priest.penance,
    "spell_holy_penance",
    "Launches a volley of holy light at the target, causing 81 Holy damage to an enemy, or 184 healing to an ally, instantly and every 1 sec for 2 sec.",
  ),
  new MultiRankTalent(
    talentNames.priest.renewedHope,
    "spell_holy_holyprotection",
    [
      "Your heals from Flash Heal, Binding Heal, Lesser Heal, Heal, Greater Heal, and Penance gain ",
      "% increased critical strike chance when cast on targets with Weakened Soul, and reduce the remaining duration of Weakened Soul on their target by ",
      " sec.",
    ],
    [
      ["2", "4", "6", "8", "10"],
      ["1", "2", "3", "4", "5"],
    ],
    talentNames.priest.soulWarding,
  ),
  null,
];

const tier6: TalentTier = [
  null,
  null,
  null,
  new MultiRankTalent(
    talentNames.priest.divineAegis,
    "spell_holy_devineaegis",
    [
      "Your critical heals create a protective shield on the target, absorbing ",
      "% of the amount healed. Lasts 12 sec.",
    ],
    [["5", "10", "15"]],
  ),
  null,
];

const tier7: TalentTier = [
  null,
  null,
  new SingleRankTalent(
    talentNames.priest.powerInfusion,
    "spell_holy_powerinfusion",
    "Infuses the target with power, increasing their spell damage and healing done by 20% for 15 sec.",
    talentNames.priest.penance,
  ),
  null,
  null,
];

export const discipline = {
  tier1,
  tier2,
  tier3,
  tier4,
  tier5,
  tier6,
  tier7,
};
