import { MultiRankTalent, SingleRankTalent } from "@/lib/classes";
import { talentNames } from "@/lib/constants";
import { TalentTier, TalentTree } from "@/lib/types";

const tier1: TalentTier = [
  null,
  null,
  new MultiRankTalent(
    talentNames.druid.naturesFocus,
    "spell_nature_healingwavegreater",
    [
      "Gives you a ",
      "% chance to avoid interruption caused by damage while casting Arcane and Nature spells.",
    ],
    [[14, 28, 42, 56, 70]],
  ),
  new MultiRankTalent(
    talentNames.druid.furor,
    "spell_holy_blessingofstamina",
    [
      "Gives you a ",
      "% chance to gain 10 Rage when you shapeshift into Bear Form or Dire Bear Form. When you shift into Cat Form, you will regain ",
      "% of the Energy you had when you were last in Cat Form, plus ",
      " Energy for each second you spent not in Bear Form, Cat Form, or Dire Bear Form, up to a maximum of ",
      " Energy.",
    ],
    [
      [20, 40, 60, 80, 100],
      [20, 40, 60, 80, 100],
      [2, 4, 6, 8, 10],
      [20, 40, 60, 80, 100],
    ],
  ),
  null,
];

const tier2: TalentTier = [
  null,
  new MultiRankTalent(
    talentNames.druid.naturalist,
    "spell_nature_healingtouch",
    [
      "Reduces the cast time of your Healing Touch spell by ",
      " sec and increases all damage you deal by ",
      "%.",
    ],
    [
      [0.1, 0.2, 0.3, 0.4, 0.5],
      [1, 2, 3, 4, 5],
    ],
  ),
  new MultiRankTalent(
    talentNames.druid.subtlety,
    "ability_eyeoftheowl",
    ["Reduces the threat generated by your Nature and Arcane spells by ", "%."],
    [[10, 20, 30]],
  ),
  new MultiRankTalent(
    talentNames.druid.naturalShapeshifter,
    "spell_nature_wispsplode",
    ["Reduces the mana cost of all shapeshifting by ", "%."],
    [[10, 20, 30]],
  ),
  null,
];

const tier3: TalentTier = [
  null,
  null,
  new MultiRankTalent(
    talentNames.druid.reflection,
    "spell_frost_windwalkon",
    ["Allows ", "% of your Mana regeneration to continue while casting."],
    [[17, 33, 50]],
  ),
  new MultiRankTalent(
    talentNames.druid.giftOfNature,
    "spell_nature_protectionformnature",
    ["Increases the effect of all your healing spells by ", "%."],
    [[2, 4, 6, 8, 10]],
  ),
  new SingleRankTalent(
    talentNames.druid.giftOfTheEarthmother,
    "spell_nature_spiritarmor",
    "Reduces the global cooldown by 0.5 seconds on your Rejuvenation, Swiftmend, and Wild Growth spells.",
  ),
];

const tier4: TalentTier = [
  null,
  null,
  new MultiRankTalent(
    talentNames.druid.tranquilSpirit,
    "spell_holy_elunesgrace",
    [
      "Reduces the mana cost of your Healing Touch and Tranquility spells by ",
      "%.",
    ],
    [[2, 4, 6, 8, 10]],
  ),
  new MultiRankTalent(
    talentNames.druid.improvedRejuvenation,
    "spell_nature_rejuvenation",
    ["Increases the effect of your Rejuvenation spell by ", "%."],
    [[5, 10, 15]],
  ),
  new SingleRankTalent(
    talentNames.druid.swiftmend,
    "inv_relics_idolofrejuvenation",
    "Instantly heals a target with an active Rejuvenation or Regrowth effect for an amount equal to the full duration of the periodic effect of one of those spells.",
  ),
];

const tier5: TalentTier = [
  null,
  new SingleRankTalent(
    talentNames.druid.naturesSwiftness,
    "spell_nature_ravenform",
    "When activated, your next Nature spell becomes an instant cast spell.",
    talentNames.druid.naturalist,
  ),
  new MultiRankTalent(
    talentNames.druid.livingSpirit,
    "spell_nature_giftofthewaterspirit",
    ["Increases your Spirit by ", "%."],
    [[5, 10, 15]],
  ),
  null,
  new MultiRankTalent(
    talentNames.druid.improvedTranquility,
    "spell_nature_tranquility",
    [
      "Reduces threat caused by Tranquility by ",
      "% and its cooldown by ",
      "%.",
    ],
    [
      [50, 100],
      [30, 60],
    ],
  ),
];

const tier6: TalentTier = [
  null,
  null,
  null,
  new MultiRankTalent(
    talentNames.druid.improvedRegrowth,
    "spell_nature_resistnature",
    ["Increases the critical effect chance of your Regrowth spell by ", "%."],
    [[10, 20, 30, 40, 50]],
    talentNames.druid.improvedRejuvenation,
  ),
  null,
];

const tier7: TalentTier = [
  null,
  null,
  new SingleRankTalent(
    talentNames.druid.wildGrowth,
    "ability_druid_flourish",
    "Heals the target and their party for 336 over 7 sec. Party members must be within 43.5 yards of target. The amount healed is applied quickly at first, and slows down as Wild Growth reaches its full duration.",
    talentNames.druid.livingSpirit,
  ),
  null,
  null,
];

export const restoration: TalentTree = {
  name: "Restoration",
  icon: "spell_nature_healingtouch",
  tiers: {
    tier1,
    tier2,
    tier3,
    tier4,
    tier5,
    tier6,
    tier7,
  },
};
