export const talentNames = {
  adrenalineRush: "Adrenaline Rush",
  aftermath: "Aftermath",
  aggression: "Aggression",
  agonizingFlames: "Agonizing Flames",
  amplifyCurse: "Amplify Curse",
  ancestralHealing: "Ancestral Healing",
  ancestralKnowledge: "Ancestral Knowledge",
  angerManagement: "Anger Management",
  anticipation: "Anticipation",
  arcaneBlast: "Arcane Blast",
  arcaneConcentration: "Arcane Concentration",
  arcaneFocus: "Arcane Focus",
  arcaneGeometry: "Arcane Geometry",
  arcaneImpact: "Arcane Impact",
  arcaneInstability: "Arcane Instability",
  arcaneMeditation: "Arcane Meditation",
  arcaneMind: "Arcane Mind",
  arcanePower: "Arcane Power",
  arcaneResilience: "Arcane Resilience",
  arcaneShielding: "Arcane Shielding",
  arcaneSubtlety: "Arcane Subtlety",
  arcticReach: "Arctic Reach",
  bane: "Bane",
  baneOfHavoc: "Bane of Havoc",
  barrage: "Barrage",
  bastion: "Bastion",
  benediction: "Benediction",
  berserk: "Berserk",
  bestialDiscipline: "Bestial Discipline",
  bestialSwiftness: "Bestial Swiftness",
  bestialWrath: "Bestial Wrath",
  bindingHeal: "Binding Heal",
  blackout: "Blackout",
  bladeFlurry: "Blade Flurry",
  blastWave: "Blast Wave",
  blessedRecovery: "Blessed Recovery",
  bloodCraze: "Blood Craze",
  bloodFrenzy: "Blood Frenzy",
  bloodthirst: "Bloodthirst",
  bloodthrill: "Bloodthrill",
  boomingVoice: "Booming Voice",
  brutalImpact: "Brutal Impact",
  burningSoul: "Burning Soul",
  callOfFlame: "Call of Flame",
  callOfThunder: "Call of Thunder",
  camouflage: "Camouflage",
  carefulAim: "Careful Aim",
  cataclysm: "Cataclysm",
  championOfTheLight: "Champion of the Light",
  cleverTraps: "Clever Traps",
  coldBlood: "Cold Blood",
  coldSnap: "Cold Snap",
  combustion: "Combustion",
  concussion: "Concussion",
  concussionBlow: "Concussion Blow",
  conflagrate: "Conflagrate",
  consecratedGround: "Consecrated Ground",
  convection: "Convection",
  conviction: "Conviction",
  counterattack: "Counterattack",
  criticalMass: "Critical Mass",
  cruelty: "Cruelty",
  curseOfExhaustion: "Curse of Exhaustion",
  cutthroat: "Cutthroat",
  darkness: "Darkness",
  deadlyAspects: "Deadly Aspects",
  deathWish: "Death Wish",
  decimation: "Decimation",
  deepWounds: "Deep Wounds",
  defiance: "Defiance",
  deflection: "Deflection",
  demonicAegis: "Demonic Aegis",
  demonicBrand: "Demonic Brand",
  demonicEmbrace: "Demonic Embrace",
  demonicEnergies: "Demonic Energies",
  demonicKnowledge: "Demonic Knowledge",
  demonicPact: "Demonic Pact",
  demonicSacrifice: "Demonic Sacrifice",
  destructiveReach: "Destructive Reach",
  deterrence: "Deterrence",
  devouringContagion: "Devouring Contagion",
  dirtyDeeds: "Dirty Deeds",
  dirtyTricks: "Dirty Tricks",
  divineAegis: "Divine Aegis",
  divineFavor: "Divine Favor",
  divineFury: "Divine Fury",
  divineIntellect: "Divine Intellect",
  divinePrecision: "Divine Precision",
  divineStrength: "Divine Strength",
  dualWieldSpecialization: "Dual Wield Specialization",
  earlyDemise: "Early Demise",
  earthbound: "Earthbound",
  earthsGrasp: "Earth's Grasp",
  eclipse: "Eclipse",
  efficiency: "Efficiency",
  elementalAlacrity: "Elemental Alacrity",
  elementalDevastation: "Elemental Devastation",
  elementalFocus: "Elemental Focus",
  elementalFury: "Elemental Fury",
  elementalPrecision: "Elemental Precision",
  elementalReach: "Elemental Reach",
  elementalWarding: "Elemental Warding",
  elementalWeapons: "Elemental Weapons",
  elusiveness: "Elusiveness",
  endurance: "Endurance",
  enduranceTraining: "Endurance Training",
  enrage: "Enrage",
  entrapment: "Entrapment",
  exposePrey: "Expose Prey",
  eyeForAnEye: "Eye for an Eye",
  eyeOfTheStorm: "Eye of the Storm",
  felConcentration: "Fel Concentration",
  felDomination: "Fel Domination",
  felVitality: "Fel Vitality",
  feralCharge: "Feral Charge",
  feralInstinct: "Feral Instinct",
  feralSwiftness: "Feral Swiftness",
  ferocity: "Ferocity",
  fingersOfFrost: "Fingers of Frost",
  fireAndBrimstone: "Fire and Brimstone",
  firePower: "Fire Power",
  flameThrowing: "Flame Throwing",
  flawlessExecution: "Flawless Execution",
  flurry: "Flurry",
  focusedFire: "Focused Fire",
  focusedRage: "Focused Rage",
  frenzy: "Frenzy",
  frostChanneling: "Frost Channeling",
  frostWarding: "Frost Warding",
  frostbite: "Frostbite",
  furiousPrecision: "Furious Precision",
  furor: "Furor",
  genesis: "Genesis",
  ghostlyStrike: "Ghostly Strike",
  giftOfNature: "Gift of Nature",
  giftOfTheEarthmother: "Gift of the Earthmother",
  goreDrinker: "Gore Drinker",
  guardianTotems: "Guardian Totems",
  guardiansFavor: "Guardian's Favor",
  hackAndSlash: "Hack and Slash",
  hawkEye: "Hawk Eye",
  healingFocus: "Healing Focus",
  healingLight: "Healing Light",
  healingWay: "Healing Way",
  heartOfTheWild: "Heart of the Wild",
  heatingUp: "Heating Up",
  heightenedSenses: "Heightened Senses",
  hemorrhage: "Hemorrhage",
  holyConduit: "Holy Conduit",
  holyNova: "Holy Nova",
  holyPower: "Holy Power",
  holyPrecision: "Holy Precision",
  holyReach: "Holy Reach",
  holyShield: "Holy Shield",
  holyShock: "Holy Shock",
  holySpecialization: "Holy Specialization",
  iceBarrier: "Ice Barrier",
  iceBlock: "Ice Block",
  iceLance: "Ice Lance",
  iceShards: "Ice Shards",
  ignite: "Ignite",
  illumination: "Illumination",
  impact: "Impact",
  impale: "Impale",
  improvedAmbush: "Improved Ambush",
  improvedArcaneShot: "Improved Arcane Shot",
  improvedAspectOfTheMonkey: "Improved Aspect of the Monkey",
  improvedBaneOfAgony: "Improved Bane of Agony",
  improvedBerserkerRage: "Improved Berserker Rage",
  improvedBlizzard: "Improved Blizzard",
  improvedBloodrage: "Improved Bloodrage",
  improvedChanneling: "Improved Channeling",
  improvedCharge: "Improved Charge",
  improvedConcussiveShot: "Improved Concussive Shot",
  improvedConeOfCold: "Improved Cone of Cold",
  improvedCorruption: "Improved Corruption",
  improvedCounterspell: "Improved Counterspell",
  improvedDisarm: "Improved Disarm",
  improvedDistract: "Improved Distract",
  improvedDrains: "Improved Drains",
  improvedEntanglingRoots: "Improved Entangling Roots",
  improvedEviscerate: "Improved Eviscerate",
  improvedExecute: "Improved Execute",
  improvedExposeArmor: "Improved Expose Armor",
  improvedFade: "Improved Fade",
  improvedFelhunter: "Improved Felhunter",
  improvedFireNova: "Improved Fire Nova",
  improvedFireWard: "Improved Fire Ward",
  improvedFireball: "Improved Fireball",
  improvedFlamestrike: "Improved Flamestrike",
  improvedFrostNova: "Improved Frost Nova",
  improvedFrostbolt: "Improved Frostbolt",
  improvedGhostWolf: "Improved Ghost Wolf",
  improvedGouge: "Improved Gouge",
  improvedHammerOfJustice: "Improved Hammer of Justice",
  improvedHamstring: "Improved Hamstring",
  improvedHealing: "Improved Healing",
  improvedHealingWave: "Improved Healing Wave",
  improvedHealthFunnel: "Improved Health Funnel",
  improvedHeroicStrike: "Improved Heroic Strike",
  improvedImp: "Improved Imp",
  improvedInnerFire: "Improved Inner Fire",
  improvedIntercept: "Improved Intercept",
  improvedJudgement: "Improved Judgement",
  improvedKick: "Improved Kick",
  improvedKidneyShot: "Improved Kidney Shot",
  improvedLifeTap: "Improved Life Tap",
  improvedLightningShield: "Improved Lightning Shield",
  improvedManaBurn: "Improved Mana Burn",
  improvedMendPet: "Improved Mend Pet",
  improvedMindBlast: "Improved Mind Blast",
  improvedMindFlay: "Improved Mind Flay",
  improvedMoonfire: "Improved Moonfire",
  improvedOverpower: "Improved Overpower",
  improvedPoisons: "Improved Poisons",
  improvedPowerWordShield: "Improved Power Word: Shield",
  improvedPsychicScream: "Improved Psychic Scream",
  improvedRegrowth: "Improved Regrowth",
  improvedReincarnation: "Improved Reincarnation",
  improvedRejuvenation: "Improved Rejuvenation",
  improvedRend: "Improved Rend",
  improvedRenew: "Improved Renew",
  improvedRevenge: "Improved Revenge",
  improvedRevivePet: "Improved Revive Pet",
  improvedRighteousFury: "Improved Righteous Fury",
  improvedSayaad: "Improved Sayaad",
  improvedScorch: "Improved Scorch",
  improvedSealOfFury: "Improved Seal of Fury",
  improvedSeals: "Improved Seals",
  improvedShadowBolt: "Improved Shadow Bolt",
  improvedShadowWordPain: "Improved Shadow Word: Pain",
  improvedShieldBash: "Improved Shield Bash",
  improvedShieldWall: "Improved Shield Wall",
  improvedShiftingPower: "Improved Shifting Power",
  improvedSinisterStrike: "Improved Sinister Strike",
  improvedSlam: "Improved Slam",
  improvedSliceAndDice: "Improved Slice and Dice",
  improvedSprint: "Improved Sprint",
  improvedStarfire: "Improved Starfire",
  improvedStings: "Improved Stings",
  improvedStormstrike: "Improved Stormstrike",
  improvedSunderArmor: "Improved Sunder Armor",
  improvedTacticalMastery: "Improved Tactical Mastery",
  improvedThunderClap: "Improved Thunder Clap",
  improvedTracking: "Improved Tracking",
  improvedTranquility: "Improved Tranquility",
  improvedVoidwalker: "Improved Voidwalker",
  improvedWingClip: "Improved Wing Clip",
  improvedWrath: "Improved Wrath",
  incinerate: "Incinerate",
  incineration: "Incineration",
  infusionOfLight: "Infusion of Light",
  initiative: "Initiative",
  innerFocus: "Inner Focus",
  insectSwarm: "Insect Swarm",
  inspiration: "Inspiration",
  instrumentOfLaw: "Instrument of Law",
  intensity: "Intensity",
  intimidation: "Intimidation",
  ironCreed: "Iron Creed",
  ironWill: "Iron Will",
  laceratingStrikes: "Lacerating Strikes",
  lastStand: "Last Stand",
  lavaBurst: "Lava Burst",
  leaderOfThePack: "Leader of the Pack",
  lethalAttacks: "Lethal Attacks",
  lethality: "Lethality",
  lightningOverload: "Lightning Overload",
  lightningReflexes: "Lightning Reflexes",
  lightsVigil: "Light's Vigil",
  lingeringRage: "Lingering Rage",
  litanyOfLight: "Litany of Light",
  livingSpirit: "Living Spirit",
  loneWolf: "Lone Wolf",
  maelstromWeapon: "Maelstrom Weapon",
  magicAbsorption: "Magic Absorption",
  malediction: "Malediction",
  malevolence: "Malevolence",
  malice: "Malice",
  manaTideTotem: "Mana Tide Totem",
  martyrdom: "Martyrdom",
  masterDemonologist: "Master Demonologist",
  masterOfDeception: "Master of Deception",
  masterOfDefense: "Master of Defense",
  masterOfElements: "Master of Elements",
  masterSummoner: "Master Summoner",
  meditation: "Meditation",
  mentalAgility: "Mental Agility",
  mentalDexterity: "Mental Dexterity",
  mentalQuickness: "Mental Quickness",
  mentalStrength: "Mental Strength",
  mindFlay: "Mind Flay",
  mindfulness: "Mindfulness",
  missileBarrage: "Missile Barrage",
  moltenSkin: "Molten Skin",
  moonfury: "Moonfury",
  moonglow: "Moonglow",
  moonkinForm: "Moonkin Form",
  mortalShots: "Mortal Shots",
  mortalStrike: "Mortal Strike",
  murder: "Murder",
  mutilate: "Mutilate",
  naturalGrace: "Natural Grace",
  naturalReaction: "Natural Reaction",
  naturalShapeshifter: "Natural Shapeshifter",
  naturalist: "Naturalist",
  naturesFocus: "Nature's Focus",
  naturesGrace: "Nature's Grace",
  naturesMajesty: "Nature's Majesty",
  naturesReach: "Nature's Reach",
  naturesSplendor: "Nature's Splendor",
  naturesSwiftness: "Nature's Swiftness",
  nightfall: "Nightfall",
  oneHandedWeaponSpecialization: "One-Handed Weapon Specialization",
  opportunity: "Opportunity",
  overgrowth: "Overgrowth",
  pandemic: "Pandemic",
  pathfinding: "Pathfinding",
  penance: "Penance",
  permafrost: "Permafrost",
  piercingHowl: "Piercing Howl",
  piercingIce: "Piercing Ice",
  powerInLight: "Power in Light",
  powerInfusion: "Power Infusion",
  prayerOfMending: "Prayer of Mending",
  precision: "Precision",
  predatorsEdge: "Predator's Edge",
  predatoryInstincts: "Predatory Instincts",
  predatoryStrikes: "Predatory Strikes",
  premeditation: "Premeditation",
  preparation: "Preparation",
  presenceOfMind: "Presence of Mind",
  primalBite: "Primal Bite",
  puncturingWounds: "Puncturing Wounds",
  purification: "Purification",
  purifyingPower: "Purifying Power",
  pursuitOfJustice: "Pursuit of Justice",
  pyroblast: "Pyroblast",
  pyroclasm: "Pyroclasm",
  quietus: "Quietus",
  rageOfTheFarseer: "Rage of the Farseer",
  ragingBlows: "Raging Blows",
  rangedWeaponSpecialization: "Ranged Weapon Specialization",
  rapidKilling: "Rapid Killing",
  rapidRecuperation: "Rapid Recuperation",
  reckoning: "Reckoning",
  redoubt: "Redoubt",
  reflection: "Reflection",
  relentlessStrikes: "Relentless Strikes",
  remorselessAttacks: "Remorseless Attacks",
  rendAndTear: "Rend and Tear",
  renewedHope: "Renewed Hope",
  repentance: "Repentance",
  resourcefulness: "Resourcefulness",
  restorativeTotems: "Restorative Totems",
  reverberation: "Reverberation",
  reverence: "Reverence",
  riposte: "Riposte",
  riptide: "Riptide",
  ruin: "Ruin",
  ruthlessness: "Ruthlessness",
  sacredArbiter: "Sacred Arbiter",
  sacredDuty: "Sacred Duty",
  sanctifiedJudgement: "Sanctified Judgement",
  savageFury: "Savage Fury",
  savageStrikes: "Savage Strikes",
  scatterShot: "Scatter Shot",
  sealFate: "Seal Fate",
  sealOfCommand: "Seal of Command",
  searingLight: "Searing Light",
  serratedBlades: "Serrated Blades",
  setup: "Setup",
  shadowAffinity: "Shadow Affinity",
  shadowAndFlame: "Shadow and Flame",
  shadowFocus: "Shadow Focus",
  shadowMastery: "Shadow Mastery",
  shadowReach: "Shadow Reach",
  shadowWeaving: "Shadow Weaving",
  shadowburn: "Shadowburn",
  shadowform: "Shadowform",
  shamanisticFocus: "Shamanistic Focus",
  sharpenedClaws: "Sharpened Claws",
  shatter: "Shatter",
  shieldSlam: "Shield Slam",
  shieldSpecialization: "Shield Specialization",
  shiftingPower: "Shifting Power",
  shreddingAttacks: "Shredding Attacks",
  silence: "Silence",
  silentResolve: "Silent Resolve",
  siphonLife: "Siphon Life",
  sniperShot: "Sniper Shot",
  soulHarvest: "Soul Harvest",
  soulLink: "Soul Link",
  soulSiphon: "Soul Siphon",
  soulWarding: "Soul Warding",
  spearingStrike: "Spearing Strike",
  spellWarding: "Spell Warding",
  spiritBond: "Spirit Bond",
  spiritOfRedemption: "Spirit of Redemption",
  spiritTap: "Spirit Tap",
  spiritWeapons: "Spirit Weapons",
  spiritualFocus: "Spiritual Focus",
  spiritualGuidance: "Spiritual Guidance",
  spiritualHealing: "Spiritual Healing",
  stormstrike: "Stormstrike",
  striderKick: "Strider Kick",
  subtlety: "Subtlety",
  summonHawk: "Summon Hawk",
  suppression: "Suppression",
  surefooted: "Surefooted",
  survivalTactics: "Survival Tactics",
  survivalist: "Survivalist",
  survivalistsDiscipline: "Survivalist's Discipline",
  sweepingStrikes: "Sweeping Strikes",
  swiftJudgement: "Swift Judgement",
  swiftmend: "Swiftmend",
  templarsBulwark: "Templar's Bulwark",
  thickHide: "Thick Hide",
  thousandCuts: "Thousand Cuts",
  thunderingStrikes: "Thundering Strikes",
  tidalFocus: "Tidal Focus",
  tidalMastery: "Tidal Mastery",
  totemicFocus: "Totemic Focus",
  toughness: "Toughness",
  tranquilSpirit: "Tranquil Spirit",
  trueshotAura: "Trueshot Aura",
  twilightFocus: "Twilight Focus",
  twinDisciplines: "Twin Disciplines",
  twistOfLight: "Twist of Light",
  twoHandedWeaponSpecialization: "Two-Handed Weapon Specialization",
  unbridledWrath: "Unbridled Wrath",
  unholyPower: "Unholy Power",
  unleashedFury: "Unleashed Fury",
  unyieldingFaith: "Unyielding Faith",
  vampiricEmbrace: "Vampiric Embrace",
  vanguard: "Vanguard",
  vengeance: "Vengeance",
  venom: "Venom",
  vigor: "Vigor",
  vilePoisons: "Vile Poisons",
  vindication: "Vindication",
  voiceOfTruth: "Voice of Truth",
  wakeOfFire: "Wake of Fire",
  wandSpecialization: "Wand Specialization",
  waterShield: "Water Shield",
  weaponExpertise: "Weapon Expertise",
  weaponmaster: "Weaponmaster",
  wildGrowth: "Wild Growth",
  wintersChill: "Winter's Chill",
  wrack: "Wrack",
} as const;
