export const talentNames = {
  mage: {
    arcaneBlast: "Arcane Blast",
    arcaneConcentration: "Arcane Concentration",
    arcaneFocus: "Arcane Focus",
    arcaneGeometry: "Arcane Geometry",
    arcaneImpact: "Arcane Impact",
    arcaneInstability: "Arcane Instability",
    arcaneMeditation: "Arcane Meditation",
    arcaneMind: "Arcane Mind",
    arcanePower: "Arcane Power",
    arcaneResilience: "Arcane Resilience",
    arcaneShielding: "Arcane Shielding",
    arcaneSubtlety: "Arcane Subtlety",
    arcticReach: "Arctic Reach",
    blastWave: "Blast Wave",
    burningSoul: "Burning Soul",
    coldSnap: "Cold Snap",
    combustion: "Combustion",
    criticalMass: "Critical Mass",
    elementalPrecision: "Elemental Precision",
    fingersOfFrost: "Fingers of Frost",
    firePower: "Fire Power",
    flameThrowing: "Flame Throwing",
    frostChanneling: "Frost Channeling",
    frostWarding: "Frost Warding",
    frostbite: "Frostbite",
    heatingUp: "Heating Up",
    iceBarrier: "Ice Barrier",
    iceBlock: "Ice Block",
    iceLance: "Ice Lance",
    iceShards: "Ice Shards",
    ignite: "Ignite",
    impact: "Impact",
    improvedBlizzard: "Improved Blizzard",
    improvedChanneling: "Improved Channeling",
    improvedConeOfCold: "Improved Cone of Cold",
    improvedCounterspell: "Improved Counterspell",
    improvedFireWard: "Improved Fire Ward",
    improvedFireball: "Improved Fireball",
    improvedFlamestrike: "Improved Flamestrike",
    improvedFrostNova: "Improved Frost Nova",
    improvedFrostbolt: "Improved Frostbolt",
    improvedScorch: "Improved Scorch",
    incineration: "Incineration",
    magicAbsorption: "Magic Absorption",
    masterOfElements: "Master of Elements",
    missileBarrage: "Missile Barrage",
    permafrost: "Permafrost",
    piercingIce: "Piercing Ice",
    presenceOfMind: "Presence of Mind",
    pyroblast: "Pyroblast",
    shatter: "Shatter",
    wakeOfFire: "Wake of Fire",
    wandSpecialization: "Wand Specialization",
    wintersChill: "Winter's Chill",
  },
  warrior: {
    angerManagement: "Anger Management",
    anticipation: "Anticipation",
    bastion: "Bastion",
    bloodCraze: "Blood Craze",
    bloodthirst: "Bloodthirst",
    bloodthrill: "Bloodthrill",
    boomingVoice: "Booming Voice",
    concussionBlow: "Concussion Blow",
    cruelty: "Cruelty",
    deathWish: "Death Wish",
    deepWounds: "Deep Wounds",
    defiance: "Defiance",
    deflection: "Deflection",
    dualWieldSpecialization: "Dual Wield Specialization",
    enrage: "Enrage",
    flurry: "Flurry",
    focusedRage: "Focused Rage",
    furiousPrecision: "Furious Precision",
    goreDrinker: "Gore Drinker",
    impale: "Impale",
    improvedBerserkerRage: "Improved Berserker Rage",
    improvedBloodrage: "Improved Bloodrage",
    improvedCharge: "Improved Charge",
    improvedDisarm: "Improved Disarm",
    improvedExecute: "Improved Execute",
    improvedHamstring: "Improved Hamstring",
    improvedHeroicStrike: "Improved Heroic Strike",
    improvedIntercept: "Improved Intercept",
    improvedOverpower: "Improved Overpower",
    improvedRend: "Improved Rend",
    improvedRevenge: "Improved Revenge",
    improvedShieldBash: "Improved Shield Bash",
    improvedShieldWall: "Improved Shield Wall",
    improvedSlam: "Improved Slam",
    improvedSunderArmor: "Improved Sunder Armor",
    improvedTacticalMastery: "Improved Tactical Mastery",
    improvedThunderClap: "Improved Thunder Clap",
    ironWill: "Iron Will",
    lastStand: "Last Stand",
    lingeringRage: "Lingering Rage",
    masterOfDefense: "Master of Defense",
    mortalStrike: "Mortal Strike",
    piercingHowl: "Piercing Howl",
    ragingBlows: "Raging Blows",
    shieldSlam: "Shield Slam",
    shieldSpecialization: "Shield Specialization",
    spearingStrike: "Spearing Strike",
    sweepingStrikes: "Sweeping Strikes",
    twoHandedWeaponSpecialization: "Two-Handed Weapon Specialization",
    unbridledWrath: "Unbridled Wrath",
    vanguard: "Vanguard",
    weaponmaster: "Weaponmaster",
  },
  rogue: {
    adrenalineRush: "Adrenaline Rush",
    aggression: "Aggression",
    bladeFlurry: "Blade Flurry",
    camouflage: "Camouflage",
    coldBlood: "Cold Blood",
    cutthroat: "Cutthroat",
    deflection: "Deflection",
    dirtyDeeds: "Dirty Deeds",
    dirtyTricks: "Dirty Tricks",
    dualWieldSpecialization: "Dual Wield Specialization",
    elusiveness: "Elusiveness",
    endurance: "Endurance",
    flawlessExecution: "Flawless Execution",
    ghostlyStrike: "Ghostly Strike",
    hackAndSlash: "Hack and Slash",
    heightenedSenses: "Heightened Senses",
    hemorrhage: "Hemorrhage",
    improvedAmbush: "Improved Ambush",
    improvedDistract: "Improved Distract",
    improvedEviscerate: "Improved Eviscerate",
    improvedExposeArmor: "Improved Expose Armor",
    improvedGouge: "Improved Gouge",
    improvedKick: "Improved Kick",
    improvedKidneyShot: "Improved Kidney Shot",
    improvedPoisons: "Improved Poisons",
    improvedSinisterStrike: "Improved Sinister Strike",
    improvedSliceAndDice: "Improved Slice and Dice",
    improvedSprint: "Improved Sprint",
    initiative: "Initiative",
    lethality: "Lethality",
    lightningReflexes: "Lightning Reflexes",
    malice: "Malice",
    masterOfDeception: "Master of Deception",
    murder: "Murder",
    mutilate: "Mutilate",
    opportunity: "Opportunity",
    precision: "Precision",
    premeditation: "Premeditation",
    preparation: "Preparation",
    puncturingWounds: "Puncturing Wounds",
    quietus: "Quietus",
    relentlessStrikes: "Relentless Strikes",
    remorselessAttacks: "Remorseless Attacks",
    riposte: "Riposte",
    ruthlessness: "Ruthlessness",
    sealFate: "Seal Fate",
    serratedBlades: "Serrated Blades",
    setup: "Setup",
    thousandCuts: "Thousand Cuts",
    venom: "Venom",
    vigor: "Vigor",
    vilePoisons: "Vile Poisons",
    weaponExpertise: "Weapon Expertise",
  },
  priest: {
    bindingHeal: "Binding Heal",
    blackout: "Blackout",
    blessedRecovery: "Blessed Recovery",
    darkness: "Darkness",
    devouringContagion: "Devouring Contagion",
    divineAegis: "Divine Aegis",
    divineFury: "Divine Fury",
    earlyDemise: "Early Demise",
    holyNova: "Holy Nova",
    holyPrecision: "Holy Precision",
    holyReach: "Holy Reach",
    holySpecialization: "Holy Specialization",
    improvedFade: "Improved Fade",
    improvedHealing: "Improved Healing",
    improvedInnerFire: "Improved Inner Fire",
    improvedManaBurn: "Improved Mana Burn",
    improvedMindBlast: "Improved Mind Blast",
    improvedMindFlay: "Improved Mind Flay",
    improvedPowerWordShield: "Improved Power Word: Shield",
    improvedPsychicScream: "Improved Psychic Scream",
    improvedRenew: "Improved Renew",
    improvedShadowWordPain: "Improved Shadow Word: Pain",
    innerFocus: "Inner Focus",
    inspiration: "Inspiration",
    litanyOfLight: "Litany of Light",
    martyrdom: "Martyrdom",
    meditation: "Meditation",
    mentalAgility: "Mental Agility",
    mentalStrength: "Mental Strength",
    mindFlay: "Mind Flay",
    penance: "Penance",
    powerInLight: "Power in Light",
    powerInfusion: "Power Infusion",
    prayerOfMending: "Prayer of Mending",
    renewedHope: "Renewed Hope",
    searingLight: "Searing Light",
    shadowAffinity: "Shadow Affinity",
    shadowFocus: "Shadow Focus",
    shadowReach: "Shadow Reach",
    shadowWeaving: "Shadow Weaving",
    shadowform: "Shadowform",
    silence: "Silence",
    silentResolve: "Silent Resolve",
    soulWarding: "Soul Warding",
    spellWarding: "Spell Warding",
    spiritOfRedemption: "Spirit of Redemption",
    spiritTap: "Spirit Tap",
    spiritualGuidance: "Spiritual Guidance",
    spiritualHealing: "Spiritual Healing",
    twilightFocus: "Twilight Focus",
    twinDisciplines: "Twin Disciplines",
    vampiricEmbrace: "Vampiric Embrace",
    wandSpecialization: "Wand Specialization",
  },
  shaman: {
    ancestralHealing: "Ancestral Healing",
    ancestralKnowledge: "Ancestral Knowledge",
    anticipation: "Anticipation",
    callOfFlame: "Call of Flame",
    callOfThunder: "Call of Thunder",
    concussion: "Concussion",
    convection: "Convection",
    earthbound: "Earthbound",
    earthsGrasp: "Earth's Grasp",
    elementalAlacrity: "Elemental Alacrity",
    elementalDevastation: "Elemental Devastation",
    elementalFocus: "Elemental Focus",
    elementalFury: "Elemental Fury",
    elementalReach: "Elemental Reach",
    elementalWarding: "Elemental Warding",
    elementalWeapons: "Elemental Weapons",
    eyeOfTheStorm: "Eye of the Storm",
    flurry: "Flurry",
    guardianTotems: "Guardian Totems",
    healingFocus: "Healing Focus",
    healingWay: "Healing Way",
    improvedFireNova: "Improved Fire Nova",
    improvedGhostWolf: "Improved Ghost Wolf",
    improvedHealingWave: "Improved Healing Wave",
    improvedLightningShield: "Improved Lightning Shield",
    improvedReincarnation: "Improved Reincarnation",
    improvedStormstrike: "Improved Stormstrike",
    lavaBurst: "Lava Burst",
    lightningOverload: "Lightning Overload",
    maelstromWeapon: "Maelstrom Weapon",
    manaTideTotem: "Mana Tide Totem",
    mentalDexterity: "Mental Dexterity",
    mentalQuickness: "Mental Quickness",
    mindfulness: "Mindfulness",
    naturalGrace: "Natural Grace",
    naturesSwiftness: "Nature's Swiftness",
    purification: "Purification",
    rageOfTheFarseer: "Rage of the Farseer",
    restorativeTotems: "Restorative Totems",
    reverberation: "Reverberation",
    riptide: "Riptide",
    shamanisticFocus: "Shamanistic Focus",
    spiritWeapons: "Spirit Weapons",
    stormstrike: "Stormstrike",
    thunderingStrikes: "Thundering Strikes",
    tidalFocus: "Tidal Focus",
    tidalMastery: "Tidal Mastery",
    totemicFocus: "Totemic Focus",
    toughness: "Toughness",
    waterShield: "Water Shield",
  },
  druid: {
    berserk: "Berserk",
    bloodFrenzy: "Blood Frenzy",
    brutalImpact: "Brutal Impact",
    eclipse: "Eclipse",
    feralCharge: "Feral Charge",
    feralInstinct: "Feral Instinct",
    feralSwiftness: "Feral Swiftness",
    ferocity: "Ferocity",
    furor: "Furor",
    genesis: "Genesis",
    giftOfNature: "Gift of Nature",
    giftOfTheEarthmother: "Gift of the Earthmother",
    heartOfTheWild: "Heart of the Wild",
    improvedEntanglingRoots: "Improved Entangling Roots",
    improvedMoonfire: "Improved Moonfire",
    improvedRegrowth: "Improved Regrowth",
    improvedRejuvenation: "Improved Rejuvenation",
    improvedShiftingPower: "Improved Shifting Power",
    improvedStarfire: "Improved Starfire",
    improvedTranquility: "Improved Tranquility",
    improvedWrath: "Improved Wrath",
    insectSwarm: "Insect Swarm",
    leaderOfThePack: "Leader of the Pack",
    livingSpirit: "Living Spirit",
    moonfury: "Moonfury",
    moonglow: "Moonglow",
    moonkinForm: "Moonkin Form",
    naturalReaction: "Natural Reaction",
    naturalShapeshifter: "Natural Shapeshifter",
    naturalist: "Naturalist",
    naturesFocus: "Nature's Focus",
    naturesGrace: "Nature's Grace",
    naturesMajesty: "Nature's Majesty",
    naturesReach: "Nature's Reach",
    naturesSplendor: "Nature's Splendor",
    naturesSwiftness: "Nature's Swiftness",
    overgrowth: "Overgrowth",
    predatoryInstincts: "Predatory Instincts",
    predatoryStrikes: "Predatory Strikes",
    primalBite: "Primal Bite",
    reflection: "Reflection",
    rendAndTear: "Rend and Tear",
    savageFury: "Savage Fury",
    sharpenedClaws: "Sharpened Claws",
    shiftingPower: "Shifting Power",
    shreddingAttacks: "Shredding Attacks",
    subtlety: "Subtlety",
    swiftmend: "Swiftmend",
    thickHide: "Thick Hide",
    tranquilSpirit: "Tranquil Spirit",
    vengeance: "Vengeance",
    wildGrowth: "Wild Growth",
  },
  warlock: {
    aftermath: "Aftermath",
    agonizingFlames: "Agonizing Flames",
    amplifyCurse: "Amplify Curse",
    bane: "Bane",
    baneOfHavoc: "Bane of Havoc",
    cataclysm: "Cataclysm",
    conflagrate: "Conflagrate",
    curseOfExhaustion: "Curse of Exhaustion",
    decimation: "Decimation",
    demonicAegis: "Demonic Aegis",
    demonicBrand: "Demonic Brand",
    demonicEmbrace: "Demonic Embrace",
    demonicEnergies: "Demonic Energies",
    demonicKnowledge: "Demonic Knowledge",
    demonicPact: "Demonic Pact",
    demonicSacrifice: "Demonic Sacrifice",
    destructiveReach: "Destructive Reach",
    felConcentration: "Fel Concentration",
    felDomination: "Fel Domination",
    felVitality: "Fel Vitality",
    fireAndBrimstone: "Fire and Brimstone",
    improvedBaneOfAgony: "Improved Bane of Agony",
    improvedCorruption: "Improved Corruption",
    improvedDrains: "Improved Drains",
    improvedFelhunter: "Improved Felhunter",
    improvedHealthFunnel: "Improved Health Funnel",
    improvedImp: "Improved Imp",
    improvedLifeTap: "Improved Life Tap",
    improvedSayaad: "Improved Sayaad",
    improvedShadowBolt: "Improved Shadow Bolt",
    improvedVoidwalker: "Improved Voidwalker",
    incinerate: "Incinerate",
    intensity: "Intensity",
    malediction: "Malediction",
    malevolence: "Malevolence",
    masterDemonologist: "Master Demonologist",
    masterSummoner: "Master Summoner",
    moltenSkin: "Molten Skin",
    nightfall: "Nightfall",
    pandemic: "Pandemic",
    pyroclasm: "Pyroclasm",
    ruin: "Ruin",
    shadowAndFlame: "Shadow and Flame",
    shadowMastery: "Shadow Mastery",
    shadowburn: "Shadowburn",
    siphonLife: "Siphon Life",
    soulHarvest: "Soul Harvest",
    soulLink: "Soul Link",
    soulSiphon: "Soul Siphon",
    suppression: "Suppression",
    unholyPower: "Unholy Power",
    wrack: "Wrack",
  },
  hunter: {
    barrage: "Barrage",
    bestialDiscipline: "Bestial Discipline",
    bestialSwiftness: "Bestial Swiftness",
    bestialWrath: "Bestial Wrath",
    carefulAim: "Careful Aim",
    cleverTraps: "Clever Traps",
    counterattack: "Counterattack",
    deadlyAspects: "Deadly Aspects",
    deflection: "Deflection",
    deterrence: "Deterrence",
    efficiency: "Efficiency",
    enduranceTraining: "Endurance Training",
    entrapment: "Entrapment",
    exposePrey: "Expose Prey",
    ferocity: "Ferocity",
    focusedFire: "Focused Fire",
    frenzy: "Frenzy",
    hawkEye: "Hawk Eye",
    improvedArcaneShot: "Improved Arcane Shot",
    improvedAspectOfTheMonkey: "Improved Aspect of the Monkey",
    improvedConcussiveShot: "Improved Concussive Shot",
    improvedMendPet: "Improved Mend Pet",
    improvedRevivePet: "Improved Revive Pet",
    improvedStings: "Improved Stings",
    improvedTracking: "Improved Tracking",
    improvedWingClip: "Improved Wing Clip",
    intimidation: "Intimidation",
    laceratingStrikes: "Lacerating Strikes",
    lethalAttacks: "Lethal Attacks",
    lightningReflexes: "Lightning Reflexes",
    loneWolf: "Lone Wolf",
    mortalShots: "Mortal Shots",
    pathfinding: "Pathfinding",
    predatorsEdge: "Predator's Edge",
    rangedWeaponSpecialization: "Ranged Weapon Specialization",
    rapidKilling: "Rapid Killing",
    rapidRecuperation: "Rapid Recuperation",
    resourcefulness: "Resourcefulness",
    savageStrikes: "Savage Strikes",
    scatterShot: "Scatter Shot",
    sniperShot: "Sniper Shot",
    spiritBond: "Spirit Bond",
    striderKick: "Strider Kick",
    summonHawk: "Summon Hawk",
    surefooted: "Surefooted",
    survivalTactics: "Survival Tactics",
    survivalist: "Survivalist",
    survivalistsDiscipline: "Survivalist's Discipline",
    trueshotAura: "Trueshot Aura",
    unleashedFury: "Unleashed Fury",
  },
  paladin: {
    anticipation: "Anticipation",
    benediction: "Benediction",
    championOfTheLight: "Champion of the Light",
    consecratedGround: "Consecrated Ground",
    conviction: "Conviction",
    deflection: "Deflection",
    divineFavor: "Divine Favor",
    divineIntellect: "Divine Intellect",
    divinePrecision: "Divine Precision",
    divineStrength: "Divine Strength",
    eyeForAnEye: "Eye for an Eye",
    guardiansFavor: "Guardian's Favor",
    healingLight: "Healing Light",
    holyConduit: "Holy Conduit",
    holyPower: "Holy Power",
    holyShield: "Holy Shield",
    holyShock: "Holy Shock",
    illumination: "Illumination",
    improvedHammerOfJustice: "Improved Hammer of Justice",
    improvedJudgement: "Improved Judgement",
    improvedRighteousFury: "Improved Righteous Fury",
    improvedSealOfFury: "Improved Seal of Fury",
    improvedSeals: "Improved Seals",
    infusionOfLight: "Infusion of Light",
    instrumentOfLaw: "Instrument of Law",
    ironCreed: "Iron Creed",
    lightsVigil: "Light's Vigil",
    oneHandedWeaponSpecialization: "One-Handed Weapon Specialization",
    precision: "Precision",
    purifyingPower: "Purifying Power",
    pursuitOfJustice: "Pursuit of Justice",
    reckoning: "Reckoning",
    redoubt: "Redoubt",
    repentance: "Repentance",
    reverence: "Reverence",
    sacredArbiter: "Sacred Arbiter",
    sacredDuty: "Sacred Duty",
    sanctifiedJudgement: "Sanctified Judgement",
    sealOfCommand: "Seal of Command",
    shieldSpecialization: "Shield Specialization",
    spiritualFocus: "Spiritual Focus",
    swiftJudgement: "Swift Judgement",
    templarsBulwark: "Templar's Bulwark",
    toughness: "Toughness",
    twistOfLight: "Twist of Light",
    twoHandedWeaponSpecialization: "Two-Handed Weapon Specialization",
    unyieldingFaith: "Unyielding Faith",
    vengeance: "Vengeance",
    vindication: "Vindication",
    voiceOfTruth: "Voice of Truth",
  },
} as const;
